/**
 * @file leds.c
 * @brief Implements the WS2812B RGB LED chain driver using RP2040 PIO.
 *
 * The PIO state machine handles the strict 800 kHz NRZ bit timing the
 * WS2812B protocol requires entirely in hardware, so leds_show() just
 * pushes pre-packed 24-bit colour words into the PIO's TX FIFO and
 * returns immediately — no CPU cycles are spent bit-banging.
 */

#include "leds.h"
#include "config.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "pico/time.h"
#include "ws2812.pio.h"   /* Generated by the Pico SDK's pioasm from ws2812.pio */

/** Local framebuffer: one packed GRB+pad word per LED, sent on leds_show(). */
static uint32_t pixel_buffer[NUM_LEDS];

/** Cached PIO offset where the ws2812 program was loaded, used at init only. */
static uint offset;

void leds_init(void)
{
    /* Load the ws2812 PIO program into the chosen PIO block and claim a
     * free state machine to run it on. pio_add_program() returns the
     * instruction memory offset the program was placed at, which the
     * generated ws2812_program_init() helper needs to wire up jumps
     * correctly. */
    offset = pio_add_program(WS2812_PIO, &ws2812_program);
    ws2812_program_init(WS2812_PIO, WS2812_SM, offset, PIN_WS2812, 800000.f, false);

    /* Clear the framebuffer and push it out once so the chain starts in a
     * known (all-off) state rather than showing power-on garbage. */
    for (int i = 0; i < NUM_LEDS; i++) {
        pixel_buffer[i] = 0;
    }
    leds_show();
}

void leds_set_pixel(uint8_t index, uint8_t r, uint8_t g, uint8_t b)
{
    if (index >= NUM_LEDS) {
        return; /* guard against out-of-range index rather than corrupting memory */
    }

    /* WS2812B expects colour data in GRB order on the wire (not RGB), and
     * the PIO program shifts out the most-significant bit first, so we
     * pre-shift the combined value left by 8 bits to align it correctly
     * within the 32-bit FIFO word the state machine consumes. */
    uint32_t grb = ((uint32_t)g << 16) | ((uint32_t)r << 8) | (uint32_t)b;
    pixel_buffer[index] = grb << 8u;
}

void leds_show(void)
{
    for (int i = 0; i < NUM_LEDS; i++) {
        /* pio_sm_put_blocking waits for FIFO space if necessary, but the
         * FIFO drains fast enough at 800 kHz that this essentially never
         * stalls in practice for an 8-LED chain. */
        pio_sm_put_blocking(WS2812_PIO, WS2812_SM, pixel_buffer[i]);
    }
}

/**
 * @brief Render one frame of the "solid blue" idle animation.
 *
 * Static colour, recomputed every call for consistency with the other
 * animation functions (cheap enough that there's no need to cache it).
 */
static void render_solid_blue(void)
{
    for (int i = 0; i < NUM_LEDS; i++) {
        leds_set_pixel(i, 0, 60, 255); /* deep blue, moderate brightness */
    }
}

/**
 * @brief Render one frame of the "breathing cyan" active-gameplay animation.
 *
 * Brightness follows a sine-like triangle wave derived from time since
 * boot, giving a smooth pulsing effect without needing floating-point
 * trig calls every frame.
 */
static void render_breathing_cyan(void)
{
    /* Triangle wave 0..255..0 over a 2-second period using only integer math. */
    uint32_t t = to_ms_since_boot(get_absolute_time()) % 2000;
    uint8_t brightness = (t < 1000) ? (uint8_t)(t * 255 / 1000)
                                     : (uint8_t)((2000 - t) * 255 / 1000);

    for (int i = 0; i < NUM_LEDS; i++) {
        leds_set_pixel(i, 0, brightness, brightness);
    }
}

/**
 * @brief Render one frame of the cycling rainbow animation.
 *
 * Each LED is offset in hue from its neighbours, and the whole pattern
 * rotates over time, producing a continuous rainbow chase along the chain.
 */
static void render_rainbow(void)
{
    uint32_t t = to_ms_since_boot(get_absolute_time());

    for (int i = 0; i < NUM_LEDS; i++) {
        /* Cheap integer "hue wheel": cycle R->G->B linearly rather than
         * full HSV conversion, which is more than this cosmetic effect needs. */
        uint16_t phase = (uint16_t)((t / 8 + i * 32) % 768);
        uint8_t r = 0, g = 0, b = 0;

        if (phase < 256) {
            r = 255 - phase; g = phase; b = 0;
        } else if (phase < 512) {
            g = 255 - (phase - 256); b = (phase - 256); r = 0;
        } else {
            b = 255 - (phase - 512); r = (phase - 512); g = 0;
        }
        leds_set_pixel(i, r, g, b);
    }
}

void leds_update_animation(led_mode_t mode)
{
    switch (mode) {
        case LED_MODE_SOLID_BLUE:     render_solid_blue();     break;
        case LED_MODE_BREATHING_CYAN: render_breathing_cyan(); break;
        case LED_MODE_RAINBOW:        render_rainbow();        break;
        default:                      render_solid_blue();     break;
    }
    leds_show();
}
